server:
  port: 0000

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka